pipelines:
  default:
    - step:
        image: hashicorp/terraform:0.13.5
        script:
          - cd tests/terraform
          - terraform init -backend-config="secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -backend-config="access_key=${AWS_OPS_ACCESS_KEY}" -input=false
          - terraform workspace select staging
          - terraform apply -var "secret_key=${AWS_STAGING_SECRET_ACCESS_KEY}" -var "access_key=${AWS_STAGING_ACCESS_KEY}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -auto-approve
          - terraform destroy -var "secret_key=${AWS_STAGING_SECRET_ACCESS_KEY}" -var "access_key=${AWS_STAGING_ACCESS_KEY}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -force
  branches:
    master:
      - step:
          script:
            - UPLOAD_URL="https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/refs/tags"
            - curl --request POST --user "${BB_AUTH_STRING}" --header "Content-Type:application/json" -d '{ "name":"'"$BITBUCKET_BUILD_NUMBER"'","target":{"hash":"'"$BITBUCKET_COMMIT"'"}}' "${UPLOAD_URL}"
      - step:
          name: Slack notification
          image: appropriate/curl
          script:
            - apk --update add git openssh
            - DESCRIPTION=$(git log --merges -2 --name-status)
            - DATA="{'text':'New release – ${BITBUCKET_BUILD_NUMBER}', 'username':'${BITBUCKET_REPO_SLUG}', 'icon_emoji':':awsm:', 'attachments':[{'title':'Descrition', 'text':'${DESCRIPTION//\'/}'}]}"
            - curl -X POST -H "Content-type:application/json" --data "${DATA}" ${SLACK_WEBHOOK_URL}
