version: 2.1
orbs:
  slack: circleci/slack@4.6.3
jobs:
  test-terraform:
    docker:
      - image: hashicorp/terraform:0.13.5
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          working_directory: tests/terraform
          command: |
            terraform init -backend-config="secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -backend-config="access_key=${AWS_OPS_ACCESS_KEY}" -input=false
            terraform workspace select << parameters.env >> || terraform workspace new << parameters.env >>
            terraform init -backend-config="secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -backend-config="access_key=${AWS_OPS_ACCESS_KEY}" -input=false
            terraform apply -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "access_key=${AWS_ACCESS_KEY_ID}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -auto-approve
            terraform destroy -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "access_key=${AWS_ACCESS_KEY_ID}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -force
  slack-notification-new-tag:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          mentions: '@data-engineers'
          template: basic_fail_1
          channel: C4H4ZV72S
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          channel: C4H4ZV72S
workflows:
  main:
    jobs:
      - test-terraform:
          name: staging_test
          context: staging
          env: staging
      - slack-notification-new-tag:
          filters:
            tags:
              only: /^v.*/
          requires:
            - staging_test