version: 2.1
orbs:
  slack: circleci/slack@4.6.3
jobs:
  test-terraform:
    docker:
      - image: hashicorp/terraform:0.13.5
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          working_directory: tests/terraform
          command: |
            terraform init -backend-config="secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -backend-config="access_key=${AWS_OPS_ACCESS_KEY}" -input=false
            terraform workspace select << parameters.env >> || terraform workspace new << parameters.env >>
            terraform init -backend-config="secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -backend-config="access_key=${AWS_OPS_ACCESS_KEY}" -input=false
            terraform apply -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "access_key=${AWS_ACCESS_KEY_ID}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -auto-approve
            terraform destroy -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "access_key=${AWS_ACCESS_KEY_ID}" -var "ops_secret_key=${AWS_OPS_SECRET_ACCESS_KEY}" -var "ops_access_key=${AWS_OPS_ACCESS_KEY}" -force
  slack-notification-new-tag:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "New release – ${CIRCLE_BUILD_NUM}, ${CIRCLE_PROJECT_REPONAME}",
                      "emoji": true
                    },
                    {
                      "type": "image",
                      "image_url": "https://api.slack.com/img/blocks/bkb_template_images/approvalsNewDevice.png",
                      "alt_text": "computer thumbnail"
                    }            
                  ]
                }
              ]
            }
          event: always
workflows:
  main:
    jobs:
      - test-terraform:
          name: staging_test
          context: staging
          env: staging
      - slack-notification-new-tag:
          context: staging
          requires:
            - staging_test
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/